version: "3.1"

services:
  cadvisor:
    image: google/cadvisor
    networks:
      - monitoring
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker/
    deploy:
      mode: global
    labels:
      container-type: "monitoring"

networks:
    monitoring:
      external:
        name: monitoring